fix the default.xml of develop branch
ROCm/ROCm pull request #3037
Opened 2024-04-17 23:11 UTC by WBobby

2024-04-22 16:02 UTC, amd-aakash approved these changes

2024-04-22 17:24 UTC, lpaoletti approved these changes

2024-04-22 17:44 UTC, samjwu requested changes
please resolve conflicts for project groups and lexicographical ordering for project names

2024-04-25 18:49 UTC, amd-aakash approved these changes

2024-04-26 20:47 UTC, samjwu commented
done in https://github.com/ROCm/ROCm/pull/3067

2024-04-26 20:47 UTC, closed without merging